baseURL = "https://unbelong.xyz/"
languageCode = "ja"
title = "unbelong"
theme = "PaperMod"

[params]
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  ShowToc = false
  profileMode = { enabled = false }
  mainSections = ["posts"]
  description = "記録と感覚の交差点、unbelongの雑記ブログ。"

[permalinks]
  posts = "/posts/:slug/"

[frontmatter]
  slug = "filename"
