baseURL = "https://masa162.github.io/masa86/"
languageCode = "ja"
title = "masa86"


[params]
description = "記録と感覚の交差点、unbelongの雑記ブログ。"

[permalinks]
posts = "/posts/:slug/"

[frontmatter]
slug = "filename"