name: Deploy to GitHub Pages

on:
  push:
    branches: [main]     # ビルドをトリガーするブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.3'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4      # ← v4 安定版
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public                 # ← Hugo の出力先
          publish_branch: gh-pages
          force_orphan: true                    # ← “最新だけ” に上書き
